// Generated by Supabase (`generate_typescript_types`). Do not edit by hand.
// Regenerate after any migration:
//   supabase gen types typescript --project-id qxhtiooitwvesnmnoeos > lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agent_traces: {
        Row: {
          business_id: string | null
          channel: string | null
          conversation_id: string | null
          created_at: string
          degraded: boolean
          duration_ms: number | null
          final_output: string | null
          id: string
          input: string | null
          steps: Json
          used_skills: string[]
        }
        Insert: {
          business_id?: string | null
          channel?: string | null
          conversation_id?: string | null
          created_at?: string
          degraded?: boolean
          duration_ms?: number | null
          final_output?: string | null
          id?: string
          input?: string | null
          steps?: Json
          used_skills?: string[]
        }
        Update: {
          business_id?: string | null
          channel?: string | null
          conversation_id?: string | null
          created_at?: string
          degraded?: boolean
          duration_ms?: number | null
          final_output?: string | null
          id?: string
          input?: string | null
          steps?: Json
          used_skills?: string[]
        }
        Relationships: []
      }
      bookings: {
        Row: {
          business_id: string
          calendar_event_id: string | null
          created_at: string
          customer_name: string
          customer_phone: string | null
          duration_minutes: number
          ends_at: string
          id: string
          notes: string | null
          service_name: string
          starts_at: string
          status: string
        }
        Insert: {
          business_id: string
          calendar_event_id?: string | null
          created_at?: string
          customer_name: string
          customer_phone?: string | null
          duration_minutes: number
          ends_at: string
          id?: string
          notes?: string | null
          service_name: string
          starts_at: string
          status?: string
        }
        Update: {
          business_id?: string
          calendar_event_id?: string | null
          created_at?: string
          customer_name?: string
          customer_phone?: string | null
          duration_minutes?: number
          ends_at?: string
          id?: string
          notes?: string | null
          service_name?: string
          starts_at?: string
          status?: string
        }
        Relationships: []
      }
      business_skills: {
        Row: {
          business_id: string
          config: Json
          enabled: boolean
          skill_name: string
          updated_at: string
        }
        Insert: {
          business_id: string
          config?: Json
          enabled?: boolean
          skill_name: string
          updated_at?: string
        }
        Update: {
          business_id?: string
          config?: Json
          enabled?: boolean
          skill_name?: string
          updated_at?: string
        }
        Relationships: []
      }
      businesses: {
        Row: {
          created_at: string | null
          hours: Json | null
          id: string
          is_default: boolean
          name: string
          phone_number_id: string | null
          public_key: string | null
          system_prompt: string
          timezone: string | null
        }
        Insert: {
          created_at?: string | null
          hours?: Json | null
          id?: string
          is_default?: boolean
          name: string
          phone_number_id?: string | null
          public_key?: string | null
          system_prompt: string
          timezone?: string | null
        }
        Update: {
          created_at?: string | null
          hours?: Json | null
          id?: string
          is_default?: boolean
          name?: string
          phone_number_id?: string | null
          public_key?: string | null
          system_prompt?: string
          timezone?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          business_id: string
          channel: string | null
          created_at: string
          email: string | null
          id: string
          name: string | null
          notes: string | null
          phone: string | null
        }
        Insert: {
          business_id: string
          channel?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          notes?: string | null
          phone?: string | null
        }
        Update: {
          business_id?: string
          channel?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          notes?: string | null
          phone?: string | null
        }
        Relationships: []
      }
      conversations: {
        Row: {
          business_id: string | null
          channel: string
          contact_handle: string | null
          created_at: string | null
          id: string
        }
        Insert: {
          business_id?: string | null
          channel?: string
          contact_handle?: string | null
          created_at?: string | null
          id?: string
        }
        Update: {
          business_id?: string | null
          channel?: string
          contact_handle?: string | null
          created_at?: string | null
          id?: string
        }
        Relationships: []
      }
      documents: {
        Row: {
          business_id: string | null
          chunk_index: number | null
          content: string
          created_at: string | null
          embedding: string | null
          filename: string | null
          id: string
          metadata: Json | null
        }
        Insert: {
          business_id?: string | null
          chunk_index?: number | null
          content: string
          created_at?: string | null
          embedding?: string | null
          filename?: string | null
          id?: string
          metadata?: Json | null
        }
        Update: {
          business_id?: string | null
          chunk_index?: number | null
          content?: string
          created_at?: string | null
          embedding?: string | null
          filename?: string | null
          id?: string
          metadata?: Json | null
        }
        Relationships: []
      }
      documents_generated: {
        Row: {
          business_id: string
          created_at: string
          currency: string
          customer_contact: string | null
          customer_name: string
          due_date: string | null
          html: string
          id: string
          items: Json
          notes: string | null
          number: string
          subtotal: number
          tax: number
          total: number
          type: string
        }
        Insert: {
          business_id: string
          created_at?: string
          currency?: string
          customer_contact?: string | null
          customer_name: string
          due_date?: string | null
          html: string
          id?: string
          items?: Json
          notes?: string | null
          number: string
          subtotal?: number
          tax?: number
          total?: number
          type: string
        }
        Update: {
          business_id?: string
          created_at?: string
          currency?: string
          customer_contact?: string | null
          customer_name?: string
          due_date?: string | null
          html?: string
          id?: string
          items?: Json
          notes?: string | null
          number?: string
          subtotal?: number
          tax?: number
          total?: number
          type?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          business_id: string
          contact_id: string | null
          created_at: string
          id: string
          source: string | null
          stage: string
          summary: string
          updated_at: string
          value_aed: number | null
        }
        Insert: {
          business_id: string
          contact_id?: string | null
          created_at?: string
          id?: string
          source?: string | null
          stage?: string
          summary: string
          updated_at?: string
          value_aed?: number | null
        }
        Update: {
          business_id?: string
          contact_id?: string | null
          created_at?: string
          id?: string
          source?: string | null
          stage?: string
          summary?: string
          updated_at?: string
          value_aed?: number | null
        }
        Relationships: []
      }
      messages: {
        Row: {
          content: string | null
          conversation_id: string | null
          created_at: string | null
          id: string
          role: string | null
        }
        Insert: {
          content?: string | null
          conversation_id?: string | null
          created_at?: string | null
          id?: string
          role?: string | null
        }
        Update: {
          content?: string | null
          conversation_id?: string | null
          created_at?: string | null
          id?: string
          role?: string | null
        }
        Relationships: []
      }
      notifications_log: {
        Row: {
          body: string
          business_id: string
          channel: string
          created_at: string
          error: string | null
          id: string
          kind: string
          provider_id: string | null
          recipient: string
          status: string
        }
        Insert: {
          body: string
          business_id: string
          channel: string
          created_at?: string
          error?: string | null
          id?: string
          kind: string
          provider_id?: string | null
          recipient: string
          status: string
        }
        Update: {
          body?: string
          business_id?: string
          channel?: string
          created_at?: string
          error?: string | null
          id?: string
          kind?: string
          provider_id?: string | null
          recipient?: string
          status?: string
        }
        Relationships: []
      }
      prompt_versions: {
        Row: {
          business_id: string
          content: string
          created_at: string
          id: string
          is_active: boolean
          note: string | null
          version: number
        }
        Insert: {
          business_id: string
          content: string
          created_at?: string
          id?: string
          is_active?: boolean
          note?: string | null
          version: number
        }
        Update: {
          business_id?: string
          content?: string
          created_at?: string
          id?: string
          is_active?: boolean
          note?: string | null
          version?: number
        }
        Relationships: []
      }
      user_businesses: {
        Row: {
          business_id: string
          created_at: string
          id: string
          role: string
          user_id: string
        }
        Insert: {
          business_id: string
          created_at?: string
          id?: string
          role?: string
          user_id: string
        }
        Update: {
          business_id?: string
          created_at?: string
          id?: string
          role?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      match_documents: {
        Args: {
          match_business_id: string
          match_count: number
          query_embedding: string
        }
        Returns: {
          content: string
          id: string
          metadata: Json
          similarity: number
        }[]
      }
      owns_business: { Args: { b: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
